# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivadoWS/LFSR/LFSR.cache/wt [current_project]
set_property parent.project_path D:/vivadoWS/LFSR/LFSR.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/vivadoWS/LFSR/LFSR.srcs/sources_1/new/LFSR.vhd
  D:/vivadoWS/LFSR/LFSR.srcs/sources_1/new/Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivadoWS/LFSR/LFSR.srcs/constrs_1/imports/XDC/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/vivadoWS/LFSR/LFSR.srcs/constrs_1/imports/XDC/Basys3_Master.xdc]


synth_design -top Main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
